/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import metier.Photo;

/**
 *
 * @author lucas
 */
public class FenetreAjoutPhoto extends javax.swing.JDialog {

    /**
     * Creates new form FenetreAjoutPhoto
     */
    private boolean modal;
    private boolean validPhoto;
    private File file;
    private String extension;
    private String filename;
    private Photo laPhoto;

    public FenetreAjoutPhoto(java.awt.Frame parent, Photo laPhoto) {
        super(parent, true);
        this.laPhoto = laPhoto;
        modal = false;
        validPhoto = false;
        initComponents();
        txtParcourirPhoto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btParcourirPhoto = new javax.swing.JButton();
        txtParcourirPhoto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbNomPhoto = new javax.swing.JLabel();
        txtNomPhoto = new javax.swing.JTextField();
        lbLieuPhoto = new javax.swing.JLabel();
        txtLieuPhoto = new javax.swing.JTextField();
        lbAnneePhoto = new javax.swing.JLabel();
        txtAnneePhoto = new javax.swing.JTextField();
        btAjouter = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();
        lbExtensionPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btParcourirPhoto.setText("Parcourir");
        btParcourirPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParcourirPhotoActionPerformed(evt);
            }
        });

        jLabel1.setText("AJOUT PHOTO");

        lbNomPhoto.setText("Nom photo :");

        lbLieuPhoto.setText("Lieu :");

        lbAnneePhoto.setText("Année :");

        btAjouter.setText("Ajouter");
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btParcourirPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtParcourirPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNomPhoto)
                                            .addComponent(lbLieuPhoto))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNomPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLieuPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAnneePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbAnneePhoto)
                                        .addGap(66, 66, 66)
                                        .addComponent(btAjouter)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAnnuler)
                                    .addComponent(lbExtensionPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btParcourirPhoto)
                    .addComponent(txtParcourirPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomPhoto)
                    .addComponent(txtNomPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbExtensionPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLieuPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLieuPhoto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnneePhoto)
                    .addComponent(txtAnneePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjouter)
                    .addComponent(btAnnuler))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btParcourirPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParcourirPhotoActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("Images", "jpg", "jpeg", "png");
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(filter);
        chooser.setDialogTitle("Choisissez une photo à ajouter...");
        int returnValue = chooser.showOpenDialog(this);
        file = chooser.getSelectedFile();
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            validPhoto = true;
            String[] nomfichier = file.getName().split("\\.");
            filename = nomfichier[0];
            extension = "." + nomfichier[1];
            lbExtensionPhoto.setText(extension);
            txtParcourirPhoto.setText(file.getPath());
            txtNomPhoto.setText(filename);
        }
    }//GEN-LAST:event_btParcourirPhotoActionPerformed

    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        try {
            if (validPhoto != true) {
                throw new Exception("Séléctionnez une photo");
            }

            String idPhoto = txtNomPhoto.getText() + extension;
            if (txtNomPhoto.getText().isEmpty()) {
                throw new Exception("Champ nom photo vide");
            }
            laPhoto.setIdPhoto(idPhoto);

            String lieuPhoto = txtLieuPhoto.getText();
            if (lieuPhoto.isEmpty()) {
                throw new Exception("Champ lieu vide");
            }
            laPhoto.setLieuPhoto(lieuPhoto);

            int anneePhoto = Integer.parseInt(txtAnneePhoto.getText());
            if (txtAnneePhoto.getText().isEmpty()) {
                throw new Exception("Champ annee vide");
            }
            laPhoto.setAnneePhoto(anneePhoto);

            modal = true;
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur ajout photo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btAjouterActionPerformed

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public boolean doModal() {
        return modal;
    }

    public File getFile() {
        return file;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btParcourirPhoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAnneePhoto;
    private javax.swing.JLabel lbExtensionPhoto;
    private javax.swing.JLabel lbLieuPhoto;
    private javax.swing.JLabel lbNomPhoto;
    private javax.swing.JTextField txtAnneePhoto;
    private javax.swing.JTextField txtLieuPhoto;
    private javax.swing.JTextField txtNomPhoto;
    private javax.swing.JTextField txtParcourirPhoto;
    // End of variables declaration//GEN-END:variables
}
