/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import accesAuxDonnees.DAOUtilisateur;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class FenetreLogin extends javax.swing.JFrame {

    private DAOUtilisateur monDaoUtilisateur;

    /**
     * Creates new form FenetreLogin
     */
    public FenetreLogin() {
        monDaoUtilisateur = new DAOUtilisateur();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtIdentifiant = new javax.swing.JTextField();
        txtMdp = new javax.swing.JPasswordField();
        lbIdentifiant = new javax.swing.JLabel();
        lbMdp = new javax.swing.JLabel();
        chbmdp = new javax.swing.JCheckBox();
        btConnecter = new javax.swing.JButton();
        btQuitter = new javax.swing.JButton();
        lbReinitialiser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(194, 133, 94));

        jLabel1.setIcon(new javax.swing.ImageIcon("Z:\\public_html\\Voicela\\voicela\\src\\icon\\Vip1.png")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon("Z:\\public_html\\Voicela\\voicela\\src\\icon\\vip2.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(101, 101, 101))
        );

        jPanel1.setBackground(new java.awt.Color(255, 237, 220));

        lbIdentifiant.setFont(new java.awt.Font("Segoe WP Light", 1, 18)); // NOI18N
        lbIdentifiant.setText("Identifiant :");

        lbMdp.setFont(new java.awt.Font("Segoe WP Light", 1, 18)); // NOI18N
        lbMdp.setText("Mot de passe :");

        chbmdp.setBackground(new java.awt.Color(255, 237, 220));
        chbmdp.setFont(new java.awt.Font("Segoe WP Light", 1, 14)); // NOI18N
        chbmdp.setText("Afficher mot de passe");
        chbmdp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbmdpItemStateChanged(evt);
            }
        });

        btConnecter.setText("Se connecter");
        btConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConnecterActionPerformed(evt);
            }
        });

        btQuitter.setText("Quitter");
        btQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitterActionPerformed(evt);
            }
        });

        lbReinitialiser.setText("Réinitialiser");
        lbReinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbReinitialiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMdp)
                    .addComponent(lbIdentifiant)
                    .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btQuitter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbmdp)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btConnecter)
                        .addGap(27, 27, 27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lbReinitialiser)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lbIdentifiant)
                .addGap(18, 18, 18)
                .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbMdp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chbmdp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConnecter)
                    .addComponent(btQuitter)
                    .addComponent(lbReinitialiser))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btQuitterActionPerformed

    private void btConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConnecterActionPerformed
        try {
            //Récupération de l'identifiant et du mot de passe
            String username = txtIdentifiant.getText();
            String mdp = String.valueOf(txtMdp.getPassword());
            if (username.isEmpty() || mdp.isEmpty()) {
                //Message erreur si champs ID et MDP vides
                JOptionPane.showMessageDialog(this, "Vous devez entrer un identifiant et un mot de passe valident !", "Erreur Identification", JOptionPane.WARNING_MESSAGE);
            } else {
                int id = monDaoUtilisateur.checkLogin(username, mdp);
                //Vérification de l'identifiant et du mot de passe
                if (id == -1) {
                    //Message erreur si ID et MDP incorrects
                    JOptionPane.showMessageDialog(this, "Identifiant ou mot de passe incorrect. Réessayez", "Identifiant Invalide", JOptionPane.WARNING_MESSAGE);
                } else {
                    //Ouverture fenetre principale si ID et MDP corrects
                    this.dispose();
                    new FenetrePrincipale(monDaoUtilisateur, id).setVisible(true);
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btConnecterActionPerformed

    private void chbmdpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbmdpItemStateChanged
        if (chbmdp.isSelected() == true) {
            txtMdp.setEchoChar((char) 0); //Si la case est cochée le mdp est affiché
        } else {
            txtMdp.setEchoChar('●'); //Si la case est décochée le mdp est caché 
        }
    }//GEN-LAST:event_chbmdpItemStateChanged

    private void lbReinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbReinitialiserActionPerformed
        //Remise à zéro de tous les champs
        txtIdentifiant.setText("");
        txtMdp.setText("");
        chbmdp.setSelected(false);
    }//GEN-LAST:event_lbReinitialiserActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConnecter;
    private javax.swing.JButton btQuitter;
    private javax.swing.JCheckBox chbmdp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbIdentifiant;
    private javax.swing.JLabel lbMdp;
    private javax.swing.JButton lbReinitialiser;
    private javax.swing.JTextField txtIdentifiant;
    private javax.swing.JPasswordField txtMdp;
    // End of variables declaration//GEN-END:variables
}
