/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metier.Film;
import modele.ModelComboBoxGenre;

/**
 *
 * @author lucas
 */
public class FenetreAjoutFilm extends javax.swing.JDialog {

    /**
     * Creates new form FenetreAjoutFilm
     */
    private ModelComboBoxGenre leDaoGenreFilm;
    private boolean modal;
    private Film leFilm;

    public FenetreAjoutFilm(java.awt.Frame parent, Film leFilm) {
        super(parent, true);
        try {
            this.leFilm = leFilm;
            leDaoGenreFilm = new ModelComboBoxGenre();
            modal = false;
            initComponents();
            cbGenreFilm.setSelectedIndex(0);
        } catch (Exception ex) {
            Logger.getLogger(FenetreAjoutFilm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitre = new javax.swing.JLabel();
        lbNumVisa = new javax.swing.JLabel();
        txtNumVisa = new javax.swing.JTextField();
        lbTitreFilm = new javax.swing.JLabel();
        txtTitreFilm = new javax.swing.JTextField();
        lbAnneeFilm = new javax.swing.JLabel();
        txtAnneeSortie = new javax.swing.JTextField();
        lbGenreFilm = new javax.swing.JLabel();
        cbGenreFilm = new javax.swing.JComboBox<>();
        btAjouter = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitre.setText("AJOUT FILM");

        lbNumVisa.setText("Visa :");

        lbTitreFilm.setText("Titre :");

        lbAnneeFilm.setText("Année :");

        lbGenreFilm.setText("Genre :");

        cbGenreFilm.setModel(leDaoGenreFilm);

        btAjouter.setText("Ajouter");
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbGenreFilm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbGenreFilm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbAnneeFilm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAnneeSortie))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNumVisa)
                                    .addComponent(lbTitreFilm))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumVisa)
                                    .addComponent(txtTitreFilm, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lbTitre))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btAnnuler)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitre)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumVisa)
                    .addComponent(txtNumVisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitreFilm)
                    .addComponent(txtTitreFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnneeFilm)
                    .addComponent(txtAnneeSortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGenreFilm)
                    .addComponent(cbGenreFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjouter)
                    .addComponent(btAnnuler))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        try {
            int numVisa = Integer.parseInt(txtNumVisa.getText());
            if (txtNumVisa.getText().isEmpty()) {
                throw new Exception("Champ numéro vide");
            }
            leFilm.setNumVisa(numVisa);

            String titreFilm = txtTitreFilm.getText();
            if (titreFilm.isEmpty()) {
                throw new Exception("Champ prenom vide");
            }
            leFilm.setTitreFilm(titreFilm);

            int anneeSortie = Integer.parseInt(txtAnneeSortie.getText());
            if (txtAnneeSortie.getText().isEmpty()) {
                throw new Exception("Champ nom vide");
            }
            leFilm.setAnneeSortie(anneeSortie);

            String genreFilm = (String) cbGenreFilm.getSelectedItem();
            leFilm.setGenreFilm(genreFilm);

            modal = true;
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur ajout", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btAjouterActionPerformed

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public boolean doModal() {
        return modal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btAnnuler;
    private javax.swing.JComboBox<String> cbGenreFilm;
    private javax.swing.JLabel lbAnneeFilm;
    private javax.swing.JLabel lbGenreFilm;
    private javax.swing.JLabel lbNumVisa;
    private javax.swing.JLabel lbTitre;
    private javax.swing.JLabel lbTitreFilm;
    private javax.swing.JTextField txtAnneeSortie;
    private javax.swing.JTextField txtNumVisa;
    private javax.swing.JTextField txtTitreFilm;
    // End of variables declaration//GEN-END:variables
}
