/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JOptionPane;
import metier.Photo;

/**
 *
 * @author lucas
 */
public class FenetreModificationPhoto extends javax.swing.JDialog {

    /**
     * Creates new form FenetreModificationPhoto
     */
    private Photo laPhoto;
    private boolean modal;
    private String extension;
    private String nomPhoto;
    private String oldIdPhoto;

    public FenetreModificationPhoto(java.awt.Frame parent, Photo laPhoto) {
        super(parent, true);
        this.laPhoto = laPhoto;
        modal = false;
        initComponents();
        String[] idPhoto = laPhoto.getIdPhoto().split("\\.");
        extension = "." + idPhoto[1];
        nomPhoto = idPhoto[0];
        txtNomPhoto.setText(nomPhoto);
        txtLieuPhoto.setText(laPhoto.getLieuPhoto());
        txtAnneePhoto.setText(String.valueOf(laPhoto.getAnneePhoto()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public boolean doModal() {
        return modal;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbNomPhoto = new javax.swing.JLabel();
        txtNomPhoto = new javax.swing.JTextField();
        lbLieuPhoto = new javax.swing.JLabel();
        txtLieuPhoto = new javax.swing.JTextField();
        lbAnneePhoto = new javax.swing.JLabel();
        txtAnneePhoto = new javax.swing.JTextField();
        btValider = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("AJOUT PHOTO");

        lbNomPhoto.setText("Nom photo :");

        lbLieuPhoto.setText("Lieu :");

        lbAnneePhoto.setText("Année :");

        btValider.setText("Valider");
        btValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValiderActionPerformed(evt);
            }
        });

        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNomPhoto)
                                    .addComponent(lbLieuPhoto))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNomPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLieuPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAnneePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbAnneePhoto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btValider)
                        .addGap(41, 41, 41)
                        .addComponent(btAnnuler))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomPhoto)
                    .addComponent(txtNomPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLieuPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLieuPhoto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnneePhoto)
                    .addComponent(txtAnneePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btValider)
                    .addComponent(btAnnuler))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValiderActionPerformed
        try {
            int reponse = JOptionPane.showConfirmDialog(this, "Valider la modification ?", "Validation", JOptionPane.YES_NO_OPTION);
            if (reponse == JOptionPane.YES_OPTION) {
                String idPhoto = txtNomPhoto.getText() + extension;
                if (txtNomPhoto.getText().isEmpty()) {
                    throw new Exception("Champ nom photo vide");
                }
                oldIdPhoto = laPhoto.getIdPhoto();
                laPhoto.setIdPhoto(idPhoto);

                String lieuPhoto = txtLieuPhoto.getText();
                if (lieuPhoto.isEmpty()) {
                    throw new Exception("Champ lieu vide");
                }
                laPhoto.setLieuPhoto(lieuPhoto);

                int anneePhoto = Integer.parseInt(txtAnneePhoto.getText());
                if (txtAnneePhoto.getText().isEmpty()) {
                    throw new Exception("Champ annee vide");
                }
                laPhoto.setAnneePhoto(anneePhoto);

                modal = true;
                this.dispose();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur modification photo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btValiderActionPerformed

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAnneePhoto;
    private javax.swing.JLabel lbLieuPhoto;
    private javax.swing.JLabel lbNomPhoto;
    private javax.swing.JTextField txtAnneePhoto;
    private javax.swing.JTextField txtLieuPhoto;
    private javax.swing.JTextField txtNomPhoto;
    // End of variables declaration//GEN-END:variables
}
