/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JOptionPane;
import metier.Casting;
import modele.ModelComboBoxFilm;
import modele.ModelComboBoxVip;
import modele.ModelJTable;
import modele.ModelJTableFilm;

/**
 *
 * @author lucas
 */
public class FenetreAjoutCasting extends javax.swing.JDialog {

    /**
     * Creates new form FenetreAjoutCasting
     */
    private boolean modal;
    private Casting leCasting;
    private ModelComboBoxFilm modelComboBoxFilm;
    private ModelComboBoxVip modelComboBoxVip;
    private ModelJTable modelTableVip;
    private ModelJTableFilm modelTableFilm;

    public FenetreAjoutCasting(java.awt.Frame parent, Casting leCasting, ModelJTable modelTableVip, ModelJTableFilm modelTableFilm) {
        super(parent, true);
        try {
            modal = false;
            this.leCasting = leCasting;
            modelComboBoxFilm = new ModelComboBoxFilm();
            modelComboBoxVip = new ModelComboBoxVip();
            this.modelTableFilm = modelTableFilm;
            this.modelTableVip = modelTableVip;
            initComponents();
            cbFilm.setSelectedIndex(0);
            cbVip.setSelectedIndex(0);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitre = new javax.swing.JLabel();
        lbFilm = new javax.swing.JLabel();
        cbFilm = new javax.swing.JComboBox<>();
        lbVip = new javax.swing.JLabel();
        cbVip = new javax.swing.JComboBox<>();
        btAjouter = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTitre.setText("AJOUT CASTING FILM");

        lbFilm.setText("Nom Film :");

        cbFilm.setModel(modelComboBoxFilm);

        lbVip.setText("Nom Vip :");

        cbVip.setModel(modelComboBoxVip);

        btAjouter.setText("Valider");
        btAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterActionPerformed(evt);
            }
        });

        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbFilm)
                                    .addComponent(lbVip))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbFilm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbVip, 0, 125, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btAjouter)
                                .addGap(28, 28, 28)
                                .addComponent(btAnnuler)
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lbTitre)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitre)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFilm)
                    .addComponent(cbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVip)
                    .addComponent(cbVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjouter)
                    .addComponent(btAnnuler))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterActionPerformed
        int numVisa = (int) modelTableFilm.getValueAt(cbFilm.getSelectedIndex(), 0);
        int numVip = (int) modelTableVip.getValueAt(cbVip.getSelectedIndex(), 0);
        leCasting.setNumVisa(numVisa);
        leCasting.setNumVip(numVip);

        modal = true;
        this.dispose();

    }//GEN-LAST:event_btAjouterActionPerformed

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public boolean doModal() {
        return modal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouter;
    private javax.swing.JButton btAnnuler;
    private javax.swing.JComboBox<String> cbFilm;
    private javax.swing.JComboBox<String> cbVip;
    private javax.swing.JLabel lbFilm;
    private javax.swing.JLabel lbTitre;
    private javax.swing.JLabel lbVip;
    // End of variables declaration//GEN-END:variables
}
